### PR TITLE
Lesson 1|2 by standford course

### PR DESCRIPTION
**Pull request by bekzod-2407**
Standford second lesson is done. I added MVC on my project and changed other little things on the view

### CODE REVIEW

**Comment by elyahk** [comment]
@bekzod-2407  Can you please give more information?
1. What has been done?
2. Which has the lesson been done?

**Comment by elyahk** [comment]
@bekzod-2407  Can you attach screenshots?

**Comment by bekzod-2407** [comment]
> @bekzod-2407 Can you please give more information?
> 
> 1. What has been done?
> 2. Which has the lesson been done?

 1) standford  second lesson is done . i added mvc on my project and  changed other little singhs on the view

**Comment by SardorK** [comment]
sfdsfvdgdgfhn gdgfef gdgb

**Review by SardorK — APPROVED** [review]

**Review by elyahk — APPROVED** [review]

**Pull request merged**
